/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an account
         * @description Creates a new account and immediately opens a session (auto-login).
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out
         * @description Invalidates the current session.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in
         * @description Authenticates and opens a session.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search the corpus
         * @description Returns paragraphs containing the requested phrase (case-insensitive exact match).
         *
         *     Each result includes the `startOffset` (inclusive) and `endOffset` (exclusive)
         *     using 0-based indexes, ready to use with `String.substring()` in Java or JavaScript.
         *
         *     Results are paginated: `size` controls how many are returned at once, `page` selects which batch. Both parameters are optional and default to the first 10 results.
         */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current user
         * @description Returns the authenticated user, or 401 if there is no active session.
         */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Account creation request */
        RegisterRequest: {
            /**
             * @description Unique username (3-50 characters)
             * @example marcel
             */
            username: string;
            /**
             * Format: email
             * @description Unique email address
             * @example marcel@example.com
             */
            email: string;
            /**
             * @description Password (15-128 characters — length over composition rules; passphrases and spaces are welcome)
             * @example Les madeleines de Combray
             */
            password: string;
        };
        /** @description Public representation of an authenticated user */
        UserResponse: {
            /**
             * Format: uuid
             * @description User identifier
             */
            uuid?: string;
            /**
             * @description Username
             * @example marcel
             */
            username?: string;
            /**
             * @description Email address
             * @example marcel@example.com
             */
            email?: string;
            /**
             * @description Role
             * @example USER
             */
            role?: string;
        };
        ProblemDetail: {
            /** Format: uri */
            type?: string;
            title?: string;
            /** Format: int32 */
            status?: number;
            detail?: string;
            /** Format: uri */
            instance?: string;
            properties?: {
                [key: string]: unknown;
            };
        };
        /** @description Login request */
        LoginRequest: {
            /**
             * @description Username
             * @example marcel
             */
            username: string;
            /**
             * @description Password
             * @example hunter2222
             */
            password: string;
        };
        /** @description A paragraph matching the search query */
        SearchHit: {
            /**
             * Format: int32
             * @description Paragraph identifier
             */
            paragraphId?: number;
            /** @description Full text of the paragraph */
            text?: string;
            /**
             * Format: int32
             * @description Start index of the match in the text (0-based, inclusive)
             * @example 3
             */
            startOffset?: number;
            /**
             * Format: int32
             * @description End index of the match in the text (0-based, exclusive)
             * @example 12
             */
            endOffset?: number;
            /**
             * @description Volume title
             * @example Du Côté de Chez Swann
             */
            volume?: string;
            /**
             * @description Part title
             * @example Combray
             */
            part?: string;
            /**
             * Format: int32
             * @description Page number in the source corpus
             * @example 1
             */
            pageNumber?: number;
        };
        /** @description Paginated response to a search query */
        SearchResponse: {
            /** @description List of matching paragraphs */
            results?: components["schemas"]["SearchHit"][];
            /**
             * Format: int64
             * @description Total number of matches across all pages
             * @example 7
             */
            total?: number;
            /**
             * Format: int32
             * @description Current page number (0-based)
             * @example 0
             */
            page?: number;
            /**
             * Format: int32
             * @description Requested page size
             * @example 10
             */
            size?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Account created and session opened */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Username or email already taken */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session invalidated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Session opened */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Invalid username or password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    search: {
        parameters: {
            query: {
                /**
                 * @description Phrase to search for (2–500 characters)
                 * @example petite madeleine
                 */
                q: string;
                /**
                 * @description Zero-based page index (default: 0). This paginates the search results, not the book's page numbers.
                 * @example 0
                 */
                page?: number;
                /**
                 * @description Number of results per batch (1–20, default 10).
                 * @example 10
                 */
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search results (empty list if no match found) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Invalid request parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authenticated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description No active session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
}
