/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List my tags
         * @description Returns the authenticated user's tags, ordered alphabetically (case-insensitive).
         */
        get: operations["list"];
        put?: never;
        /**
         * Create a tag
         * @description Creates a tag ahead of tagging any quote. 409 if a tag with the same name (case-insensitive) already exists for this user.
         */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List my quote selections
         * @description Returns the authenticated user's quotes, most recent first. Filterable by tagId.
         */
        get: operations["list_1"];
        put?: never;
        /**
         * Save a quote selection
         * @description Saves a selection of text found in a paragraph (whole paragraph or a substring),
         *     with optional tags. The server re-validates that `selectedText` matches the paragraph's actual text at the given offsets, rejecting the request otherwise.
         */
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quotes/{id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a tag to a quote
         * @description Attaches a tag (by name, created if it doesn't exist yet) to an existing quote. Idempotent: adding a tag already attached does nothing.
         */
        post: operations["addTag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an account
         * @description Creates a new account and immediately opens a session (auto-login).
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change password
         * @description Changes the password of the currently authenticated user. Requires the current password to be re-supplied and re-verified — never a change on the session alone. Invalidates every other active session for the account; the current one stays open.
         */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password-reset/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a password reset
         * @description Sends a reset link by email if the address matches an account. Always returns the same generic response, whether or not it does — this endpoint never reveals account existence.
         */
        post: operations["requestReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm a password reset
         * @description Sets a new password from a valid reset token and opens a session (auto-login, same pattern as register). Invalidates every other active session for the account.
         */
        post: operations["confirmReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out
         * @description Invalidates the current session.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in
         * @description Authenticates and opens a session.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/email/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm an email address
         * @description Marks the account's email as verified from a valid confirmation token. Does not require an active session — the link may be opened on a different device/browser than the one used to register.
         */
        post: operations["confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a tag
         * @description Deletes a tag and detaches it from every quote that had it (cascade). Quotes themselves are not affected — only this tag disappears from their tag list.
         */
        delete: operations["delete"];
        options?: never;
        head?: never;
        /**
         * Rename a tag
         * @description Renames a tag. 409 if another tag with the same name (case-insensitive) already exists for this user; renaming to the same tag's own name with different casing succeeds.
         */
        patch: operations["rename"];
        trace?: never;
    };
    "/api/quotes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a quote selection
         * @description Deletes a quote and all its tag associations. 404 if it doesn't exist or doesn't belong to the authenticated user.
         */
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        /**
         * Update a quote's personal comment
         * @description Sets or clears the authenticated user's private comment on a quote. A blank or omitted comment clears it (stored as null).
         */
        patch: operations["updateComment"];
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search the corpus
         * @description Returns paragraphs containing the requested phrase (case-insensitive exact match).
         *
         *     Each result includes the `startOffset` (inclusive) and `endOffset` (exclusive)
         *     using 0-based indexes, ready to use with `String.substring()` in Java or JavaScript.
         *
         *     Results are paginated: `size` controls how many are returned at once, `page` selects which batch. Both parameters are optional and default to the first 10 results.
         */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quotes/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get my personal timeline
         * @description Returns every one of the authenticated user's saved quotes, positioned on the work's structure (volume, page) — unpaginated, unlike list(). Filterable by tagId, same semantics as list().
         */
        get: operations["timeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current user
         * @description Returns the authenticated user, or 401 if there is no active session.
         */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quotes/{id}/tags/{tagId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a tag from a quote
         * @description Detaches a tag from a quote. No floor on the number of tags — a quote can end up with zero.
         */
        delete: operations["removeTag"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Request to create a tag ahead of tagging any quote */
        CreateTagRequest: {
            /**
             * @description Tag name, unique per user (case-insensitive after trimming)
             * @example Combray
             */
            name: string;
        };
        /** @description A personal tag */
        TagResponse: {
            /**
             * Format: int32
             * @description Tag identifier
             * @example 12
             */
            id?: number;
            /**
             * @description Tag name, as entered by the user (trimmed, original casing preserved)
             * @example Combray
             */
            name?: string;
        };
        ProblemDetail: {
            /** Format: uri */
            type?: string;
            title?: string;
            /** Format: int32 */
            status?: number;
            detail?: string;
            /** Format: uri */
            instance?: string;
            properties?: {
                [key: string]: unknown;
            };
        };
        /** @description Request to save a quote selection, with optional tags */
        CreateQuoteSelectionRequest: {
            /**
             * Format: int32
             * @description Paragraph the selection belongs to
             * @example 42
             */
            paragraphId?: number;
            /**
             * Format: int32
             * @description Start offset within the paragraph text (inclusive, 0-based)
             * @example 0
             */
            startOffset?: number;
            /**
             * Format: int32
             * @description End offset within the paragraph text (exclusive, 0-based)
             * @example 120
             */
            endOffset?: number;
            /** @description Selected text — must match the paragraph exactly at the given offsets; can be the whole paragraph */
            selectedText: string;
            /** @description Tag names to attach, created if they don't exist yet for this user. Optional — a quote can be saved without any tag. */
            tagNames?: string[];
        };
        /** @description A saved quote selection */
        QuoteSelectionResponse: {
            /**
             * Format: int32
             * @description Quote selection identifier
             * @example 7
             */
            id?: number;
            /**
             * Format: int32
             * @description Paragraph the selection belongs to
             * @example 42
             */
            paragraphId?: number;
            /**
             * Format: int32
             * @description Start offset within the paragraph text (inclusive, 0-based)
             * @example 0
             */
            startOffset?: number;
            /**
             * Format: int32
             * @description End offset within the paragraph text (exclusive, 0-based)
             * @example 120
             */
            endOffset?: number;
            /** @description Selected text */
            selectedText?: string;
            /**
             * @description Personal comment on this quote, or null if none
             * @example Passage qui résonne encore aujourd'hui
             */
            comment?: string;
            /** @description Tags attached to this quote (possibly empty — tagging is optional) */
            tags?: components["schemas"]["TagResponse"][];
            /**
             * Format: date-time
             * @description When this quote was saved
             */
            createdAt?: string;
        };
        /** @description Request to attach a tag to a quote selection, by name */
        AddTagRequest: {
            /**
             * @description Tag name — reused if it already exists for this user, created otherwise
             * @example Combray
             */
            name: string;
        };
        /** @description Account creation request */
        RegisterRequest: {
            /**
             * @description Unique username (3-50 characters)
             * @example marcel
             */
            username: string;
            /**
             * Format: email
             * @description Unique email address
             * @example marcel@example.com
             */
            email: string;
            /**
             * @description Password (15-128 characters — length over composition rules; passphrases and spaces are welcome)
             * @example Les madeleines de Combray
             */
            password: string;
        };
        /** @description Public representation of an authenticated user */
        UserResponse: {
            /**
             * Format: uuid
             * @description User identifier
             */
            uuid?: string;
            /**
             * @description Username
             * @example marcel
             */
            username?: string;
            /**
             * @description Email address
             * @example marcel@example.com
             */
            email?: string;
            /**
             * @description Role
             * @example USER
             */
            role?: string;
            /** @description Whether the account's email address has been confirmed */
            emailVerified?: boolean;
        };
        /** @description Password change for the currently authenticated user */
        PasswordChangeRequest: {
            /** @description Current password, re-verified before any change */
            currentPassword: string;
            /**
             * @description New password (15-128 characters — length over composition rules; passphrases and spaces are welcome)
             * @example Le temps retrouve enfin
             */
            newPassword: string;
        };
        /** @description Password reset request (forgot password) */
        PasswordResetRequestRequest: {
            /**
             * Format: email
             * @description Account email address
             * @example marcel@example.com
             */
            email: string;
        };
        /** @description Generic confirmation message */
        MessageResponse: {
            /**
             * @description Human-readable message
             * @example If an account exists for this email, a reset link has been sent.
             */
            message?: string;
        };
        /** @description Password reset confirmation */
        PasswordResetConfirmRequest: {
            /** @description Reset token received by email */
            token: string;
            /**
             * @description New password (15-128 characters — length over composition rules; passphrases and spaces are welcome)
             * @example Les madeleines de Combray
             */
            newPassword: string;
        };
        /** @description Login request */
        LoginRequest: {
            /**
             * @description Username
             * @example marcel
             */
            username: string;
            /**
             * @description Password
             * @example hunter2222
             */
            password: string;
        };
        /** @description Email confirmation */
        EmailVerificationConfirmRequest: {
            /** @description Confirmation token received by email */
            token: string;
        };
        /** @description Request to rename an existing tag */
        RenameTagRequest: {
            /**
             * @description New tag name, unique per user (case-insensitive after trimming)
             * @example Jalousie
             */
            name: string;
        };
        /** @description Request to set or clear a quote's personal comment */
        UpdateQuoteCommentRequest: {
            /**
             * @description New comment, or null/blank to clear it
             * @example Passage qui résonne encore aujourd'hui
             */
            comment?: string;
        };
        /** @description A paragraph matching the search query */
        SearchHit: {
            /**
             * Format: int32
             * @description Paragraph identifier
             */
            paragraphId?: number;
            /** @description Full text of the paragraph */
            text?: string;
            /**
             * Format: int32
             * @description Start index of the match in the text (0-based, inclusive)
             * @example 3
             */
            startOffset?: number;
            /**
             * Format: int32
             * @description End index of the match in the text (0-based, exclusive)
             * @example 12
             */
            endOffset?: number;
            /**
             * @description Volume title
             * @example Du Côté de Chez Swann
             */
            volume?: string;
            /**
             * @description Part title
             * @example Combray
             */
            part?: string;
            /**
             * Format: int32
             * @description Page number in the source corpus
             * @example 1
             */
            pageNumber?: number;
        };
        /** @description Paginated response to a search query */
        SearchResponse: {
            /** @description List of matching paragraphs */
            results?: components["schemas"]["SearchHit"][];
            /**
             * Format: int64
             * @description Total number of matches across all pages
             * @example 7
             */
            total?: number;
            /**
             * Format: int32
             * @description Current page number (0-based)
             * @example 0
             */
            page?: number;
            /**
             * Format: int32
             * @description Requested page size
             * @example 10
             */
            size?: number;
        };
        /** @description Paginated list of the current user's quote selections */
        QuoteSelectionListResponse: {
            /** @description List of quote selections */
            results?: components["schemas"]["QuoteSelectionResponse"][];
            /**
             * Format: int64
             * @description Total number of matches across all pages
             * @example 3
             */
            total?: number;
            /**
             * Format: int32
             * @description Current page number (0-based)
             * @example 0
             */
            page?: number;
            /**
             * Format: int32
             * @description Requested page size
             * @example 10
             */
            size?: number;
        };
        /** @description A saved quote positioned on the personal timeline */
        TimelineQuote: {
            /**
             * Format: int32
             * @description Quote selection identifier
             * @example 7
             */
            id?: number;
            /**
             * Format: int32
             * @description Paragraph the selection belongs to
             * @example 42
             */
            paragraphId?: number;
            /**
             * Format: int32
             * @description Page this quote's paragraph appears on, used to position its bookmark
             * @example 145
             */
            pageNumber?: number;
            /**
             * Format: int32
             * @description Volume this quote's paragraph belongs to
             * @example 2
             */
            volumeId?: number;
            /** @description Selected text */
            selectedText?: string;
            /**
             * @description Personal comment on this quote, or null if none
             * @example Passage qui résonne encore aujourd'hui
             */
            comment?: string;
            /** @description Tags attached to this quote (possibly empty — tagging is optional) */
            tags?: components["schemas"]["TagResponse"][];
            /**
             * Format: date-time
             * @description When this quote was saved
             */
            createdAt?: string;
        };
        /** @description The user's saved quotes positioned on the work's structure, for the personal timeline */
        TimelineResponse: {
            /** @description All 7 volumes, always present regardless of whether they contain any saved quote */
            volumes?: components["schemas"]["TimelineVolume"][];
            /** @description The user's saved quotes, ordered by their position in the work */
            quotes?: components["schemas"]["TimelineQuote"][];
        };
        /** @description A volume of the work, with the page range it spans (used to draw delimiters and position bookmarks) */
        TimelineVolume: {
            /**
             * Format: int32
             * @description Volume identifier
             * @example 2
             */
            id?: number;
            /**
             * @description Volume title
             * @example À l'Ombre des Jeunes Filles en Fleurs
             */
            title?: string;
            /**
             * Format: int32
             * @description Order of this volume in the work (1-based)
             * @example 2
             */
            position?: number;
            /**
             * Format: int32
             * @description First page of this volume
             * @example 104
             */
            minPage?: number;
            /**
             * Format: int32
             * @description Last page of this volume
             * @example 183
             */
            maxPage?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tags */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagResponse"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTagRequest"];
            };
        };
        responses: {
            /** @description Tag created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagResponse"];
                };
            };
            /** @description Invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Tag name already exists for this user */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                /**
                 * @description Only return quotes tagged with this tag id. A tagId that doesn't exist or belongs to another user yields an empty list, not an error.
                 * @example 12
                 */
                tagId?: number;
                /**
                 * @description Zero-based page index (default: 0)
                 * @example 0
                 */
                page?: number;
                /**
                 * @description Number of results per batch (1–20, default 10)
                 * @example 10
                 */
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Quote selections (empty list if none match) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteSelectionListResponse"];
                };
            };
            /** @description Invalid request parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateQuoteSelectionRequest"];
            };
        };
        responses: {
            /** @description Quote saved */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteSelectionResponse"];
                };
            };
            /** @description Invalid request body, or selectedText/offsets don't match the paragraph */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Paragraph not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    addTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddTagRequest"];
            };
        };
        responses: {
            /** @description Updated quote selection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteSelectionResponse"];
                };
            };
            /** @description Invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Quote not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Account created and session opened */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Username or email already taken */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeRequest"];
            };
        };
        responses: {
            /** @description Password changed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Not authenticated, or current password incorrect */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    requestReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequestRequest"];
            };
        };
        responses: {
            /** @description Request accepted (generic response) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    confirmReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirmRequest"];
            };
        };
        responses: {
            /** @description Password changed, session opened */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Invalid request body, or invalid/expired token */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session invalidated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Session opened */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Invalid username or password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    confirm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailVerificationConfirmRequest"];
            };
        };
        responses: {
            /** @description Email confirmed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request body, or invalid/expired token */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tag deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Tag not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    rename: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameTagRequest"];
            };
        };
        responses: {
            /** @description Tag renamed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagResponse"];
                };
            };
            /** @description Invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Tag not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Another tag with this name already exists for this user */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Quote deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Quote not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    updateComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateQuoteCommentRequest"];
            };
        };
        responses: {
            /** @description Updated quote selection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteSelectionResponse"];
                };
            };
            /** @description Invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Quote not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    search: {
        parameters: {
            query: {
                /**
                 * @description Phrase to search for (2–500 characters)
                 * @example petite madeleine
                 */
                q: string;
                /**
                 * @description Zero-based page index (default: 0). This paginates the search results, not the book's page numbers.
                 * @example 0
                 */
                page?: number;
                /**
                 * @description Number of results per batch (1–20, default 10).
                 * @example 10
                 */
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search results (empty list if no match found) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Invalid request parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    timeline: {
        parameters: {
            query?: {
                /**
                 * @description Only return quotes tagged with this tag id. A tagId that doesn't exist or belongs to another user yields an empty quotes list, not an error.
                 * @example 12
                 */
                tagId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Timeline data (empty quotes list if none match; volumes are always present) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineResponse"];
                };
            };
            /** @description Invalid request parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authenticated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description No active session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    removeTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                tagId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tag removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Quote not found, or tag not attached to this quote */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
}
